from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.table import Table


console = Console()


def _severity_display(severity: str) -> str:
    """Format issue severity for Rich output."""

    if severity == "severe":
        return "[bold red]SEVERE[/bold red]"

    if severity == "high":
        return "[red]HIGH[/red]"

    if severity == "medium":
        return "[yellow]MEDIUM[/yellow]"

    return "[dim]LOW[/dim]"


def _score_style(score: int) -> tuple[str, str]:
    """Return score style and status icon."""

    if score >= 90:
        return "bold green", "🟢"

    if score >= 75:
        return "bold yellow", "🟡"

    if score >= 60:
        return "bold yellow", "🟠"

    return "bold red", "🔴"


def render_header() -> None:
    """Render DatasetDNA header."""

    console.print()

    console.print(
        Panel.fit(
            "[bold cyan]🧬 DatasetDNA[/bold cyan]\n"
            "[bold white]Dataset Health Report[/bold white]",
            border_style="cyan",
        )
    )


def render_health_score(health: dict[str, Any]) -> None:
    """Render overall dataset health score."""

    score = int(health["score"])
    grade = health["grade"]
    issue_count = health["issue_count"]

    score_style, status_icon = _score_style(score)

    content = (
        f"{status_icon} [bold white]Health Score[/bold white]\n\n"
        f"[{score_style}]{score} / 100[/{score_style}]\n"
        f"[bold white]{grade}[/bold white]\n\n"
        f"[dim]{issue_count} issue(s) detected[/dim]"
    )

    console.print()

    console.print(
        Panel(
            content,
            title="🧬 Dataset Health",
            border_style="cyan",
            expand=False,
        )
    )


def render_health_findings(
    health: dict[str, Any],
) -> None:
    """Render health findings generated by the scoring layer."""

    issues = health.get("issues", [])

    console.print()

    if not issues:
        console.print(
            Panel(
                "[bold green]✓ No significant "
                "data-quality issues detected.[/bold green]",
                title="Health Findings",
                border_style="green",
            )
        )
        return

    table = Table(
        title="Health Findings",
        show_header=True,
        header_style="bold cyan",
    )

    table.add_column("Severity")
    table.add_column("Issue")
    table.add_column("Details")

    for issue in issues:

        severity = issue.get("severity", "low")

        details = ""

        if issue["type"] == "missing":
            details = (
                f"Column: {issue['column']} | "
                f"Missing: {issue['value']}%"
            )

        elif issue["type"] == "duplicates":
            details = (
                f"Duplicate rows: "
                f"{issue['value']}%"
            )

        elif issue["type"] == "outliers":
            details = (
                f"Column: {issue['column']} | "
                f"Outliers: {issue['value']}%"
            )

        elif issue["type"] == "correlation":
            columns = issue["columns"]

            details = (
                f"{columns[0]} ↔ {columns[1]} | "
                f"|r| = {issue['value']}"
            )

        elif issue["type"] == "target_imbalance":
            details = (
                f"Imbalance ratio: "
                f"{issue['value']}:1"
            )

        table.add_row(
            _severity_display(severity),
            issue["message"],
            details,
        )

    console.print(table)


def render_overview(
    overview: dict[str, Any],
    missing: dict[str, Any],
    duplicates: dict[str, Any],
) -> None:
    """Render dataset overview."""

    table = Table(
        title="Dataset Overview",
        show_header=True,
        header_style="bold cyan",
    )

    table.add_column("Metric")
    table.add_column("Value")

    table.add_row(
        "Rows",
        str(overview["rows"]),
    )

    table.add_row(
        "Columns",
        str(overview["columns"]),
    )

    table.add_row(
        "Memory",
        f'{overview["memory_usage_mb"]} MB',
    )

    table.add_row(
        "Missing Cells",
        str(missing["total_missing_cells"]),
    )

    table.add_row(
        "Duplicate Rows",
        str(duplicates["duplicate_count"]),
    )

    table.add_row(
        "Duplicate %",
        f'{duplicates["duplicate_percentage"]}%',
    )

    console.print()
    console.print(table)


def render_schema(
    schema: dict[str, Any],
) -> None:
    """Render dataset schema."""

    table = Table(
        title="Schema",
        show_header=True,
        header_style="bold cyan",
    )

    table.add_column("Column")
    table.add_column("Data Type")

    for column, dtype in schema.items():
        table.add_row(
            column,
            dtype,
        )

    console.print()
    console.print(table)


def render_missing(
    missing: dict[str, Any],
) -> None:
    """Render missing-value analysis."""

    table = Table(
        title="Missing Values",
        show_header=True,
        header_style="bold cyan",
    )

    table.add_column("Column")
    table.add_column("Missing Count")
    table.add_column("Missing %")

    for column, result in missing["columns"].items():
        table.add_row(
            column,
            str(result["count"]),
            f'{result["percentage"]}%',
        )

    console.print()
    console.print(table)


def render_cardinality(
    cardinality: dict[str, Any],
) -> None:
    """Render cardinality analysis."""

    table = Table(
        title="Cardinality",
        show_header=True,
        header_style="bold cyan",
    )

    table.add_column("Column")
    table.add_column("Unique Values")
    table.add_column("Unique %")

    for column, result in cardinality.items():
        table.add_row(
            column,
            str(result["unique_count"]),
            f'{result["unique_percentage"]}%',
        )

    console.print()
    console.print(table)


def render_numerical(
    numerical: dict[str, Any],
) -> None:
    """Render numerical analysis."""

    console.print()

    if not numerical:
        console.print(
            Panel(
                "No numerical columns detected.",
                title="Numerical Analysis",
            )
        )
        return

    table = Table(
        title="Numerical Analysis",
        show_header=True,
        header_style="bold cyan",
    )

    table.add_column("Column")
    table.add_column("Mean")
    table.add_column("Median")
    table.add_column("Std")
    table.add_column("Min")
    table.add_column("Max")
    table.add_column("Skew")

    for column, result in numerical.items():
        table.add_row(
            column,
            str(result["mean"]),
            str(result["median"]),
            str(result["std"]),
            str(result["min"]),
            str(result["max"]),
            str(result["skewness"]),
        )

    console.print(table)


def render_categorical(
    categorical: dict[str, Any],
) -> None:
    """Render categorical analysis."""

    console.print()

    if not categorical:
        console.print(
            Panel(
                "No categorical columns detected.",
                title="Categorical Analysis",
            )
        )
        return

    table = Table(
        title="Categorical Analysis",
        show_header=True,
        header_style="bold cyan",
    )

    table.add_column("Column")
    table.add_column("Unique Values")
    table.add_column("Top Categories")

    for column, result in categorical.items():

        categories = result["categories"]

        sorted_categories = sorted(
            categories.items(),
            key=lambda item: item[1]["count"],
            reverse=True,
        )

        top_categories = sorted_categories[:5]

        category_text = "\n".join(
            f"{category}: "
            f"{details['count']} "
            f"({details['percentage']}%)"
            for category, details in top_categories
        )

        table.add_row(
            column,
            str(result["unique_count"]),
            category_text if category_text else "No values",
        )

    console.print(table)


def render_outliers(
    outliers: dict[str, Any],
) -> None:
    """Render outlier analysis."""

    console.print()

    if not outliers:
        console.print(
            Panel(
                "No numerical columns available "
                "for outlier analysis.",
                title="Outlier Analysis",
            )
        )
        return

    table = Table(
        title="Outlier Analysis",
        show_header=True,
        header_style="bold cyan",
    )

    table.add_column("Column")
    table.add_column("Outliers")
    table.add_column("Outlier %")
    table.add_column("Lower Bound")
    table.add_column("Upper Bound")

    for column, result in outliers.items():
        table.add_row(
            column,
            str(result["outlier_count"]),
            f'{result["outlier_percentage"]}%',
            str(result["lower_bound"]),
            str(result["upper_bound"]),
        )

    console.print(table)


def render_correlations(
    correlations: dict[str, Any],
) -> None:
    """Render numerical correlations and categorical associations."""

    numeric_correlations = correlations.get(
        "numeric",
        [],
    )

    console.print()

    if numeric_correlations:

        table = Table(
            title="Numerical Correlations",
            show_header=True,
            header_style="bold cyan",
        )

        table.add_column("Column 1")
        table.add_column("Column 2")
        table.add_column("Pearson")

        for result in numeric_correlations:
            table.add_row(
                result["column_1"],
                result["column_2"],
                str(result["pearson"]),
            )

        console.print(table)

    else:
        console.print(
            Panel(
                "No numerical column pairs available.",
                title="Numerical Correlations",
            )
        )

    categorical_correlations = correlations.get(
        "categorical",
        [],
    )

    if categorical_correlations:

        console.print()

        table = Table(
            title="Categorical Associations",
            show_header=True,
            header_style="bold cyan",
        )

        table.add_column("Column 1")
        table.add_column("Column 2")
        table.add_column("Cramer's V")

        for result in categorical_correlations:
            table.add_row(
                result["column_1"],
                result["column_2"],
                str(result["cramers_v"]),
            )

        console.print(table)


def render_target(
    target: dict[str, Any],
) -> None:
    """Render target-column analysis."""

    table = Table(
        title="Target Analysis",
        show_header=True,
        header_style="bold cyan",
    )

    table.add_column("Metric")
    table.add_column("Value")

    if not target["provided"]:

        table.add_row(
            "Target",
            "Not provided",
        )

    elif "error" in target:

        table.add_row(
            "Target",
            target["column"],
        )

        table.add_row(
            "Status",
            target["error"],
        )

    elif target.get("type") == "empty":

        table.add_row(
            "Target",
            target["column"],
        )

        table.add_row(
            "Status",
            "Target contains no non-null values.",
        )

    else:

        table.add_row(
            "Target",
            target["column"],
        )

        table.add_row(
            "Type",
            target["type"],
        )

        table.add_row(
            "Classes",
            str(target["class_count"]),
        )

        imbalance_ratio = target["imbalance_ratio"]

        if imbalance_ratio is not None:
            table.add_row(
                "Imbalance Ratio",
                f"{imbalance_ratio}:1",
            )
        else:
            table.add_row(
                "Imbalance Ratio",
                "N/A",
            )

        distribution = target["class_distribution"]

        for category, details in distribution.items():
            table.add_row(
                f"Class: {category}",
                f'{details["count"]} '
                f'({details["percentage"]}%)',
            )

    console.print()
    console.print(table)


def render_completion() -> None:
    """Render successful completion message."""

    console.print()

    console.print(
        Panel(
            "[bold green]✓ DatasetDNA analysis "
            "completed successfully.[/bold green]",
            border_style="green",
        )
    )

    console.print()


def render_report(
    results: dict[str, Any],
    health: dict[str, Any],
) -> None:
    """
    Render the complete DatasetDNA console report.

    This function only renders data. It does not perform
    profiling or scoring.
    """

    render_header()

    render_health_score(health)

    render_health_findings(health)

    render_overview(
        results["overview"],
        results["missing"],
        results["duplicates"],
    )

    render_schema(
        results["schema"],
    )

    render_missing(
        results["missing"],
    )

    render_cardinality(
        results["cardinality"],
    )

    render_numerical(
        results["numerical"],
    )

    render_categorical(
        results["categorical"],
    )

    render_outliers(
        results["outliers"],
    )

    render_correlations(
        results["correlations"],
    )

    render_target(
        results["target"],
    )

    render_completion()